### ISSUE TITLE
How use?

### ISSUE THREAD

**Issue by Sergey2707** [RantsRoamer/xmr-stak-hide#1]
Hello, sat the day trying to hide the console window, where the parameter --hide just did not shove it all down (windows 10). Can you please instructions on how to hide the console on windows. Help plz!

**Comment by RantsRoamer** [comment]
Just tested the current build on a windows 10 machine, xmr-stak-hide --hide is working, are you getting any errors or what are you seeing on the screen?

**Comment by Sergey2707** [comment]
please tell me where to insert this parameter (in the startup parameters, config or where)

**Comment by RantsRoamer** [comment]
add it to the end of the command line.  Example:  c:\folder\xmr-stak-hide --hide

**Comment by Sergey2707** [comment]
![1](https://user-images.githubusercontent.com/36745123/36564021-f438785e-182c-11e8-9bac-8ee711f2726e.png)
![2](https://user-images.githubusercontent.com/36745123/36564025-f66c6a4a-182c-11e8-9b20-31711a84259d.png)

**Comment by brandonjamesmarshall** [comment]
Is there any way the -hide command can be compiled into the exe, so I can just double click on the exe file  and have it autohide that way?
