### ISSUE TITLE
Hide by default?

### ISSUE THREAD

**Issue by brandonjamesmarshall** [RantsRoamer/xmr-stak-hide#2]
Is there any way the -hide command can be compiled into the exe, so I can just double click on the exe file and have it autohide right away?

**Comment by RantsRoamer** [comment]
If you like I can make a custom version to do that.

**Comment by brandonjamesmarshall** [comment]
That would be awesome! Might I suggest adding it as an option in CMakeLists.txt so it can be compiled with or without it?

**Comment by RantsRoamer** [comment]
Just going to make it a one off version, ill add it to the options at another time.

**Comment by brandonjamesmarshall** [comment]
Works for me!

**Comment by RantsRoamer** [comment]
You can get the compiled version in releases:
https://github.com/RantsRoamer/xmr-stak-hide/releases

**Comment by RantsRoamer** [comment]
Should your feel like donating for the work:
44eiagmgb2nQpPC5o8Hp5615bqzSpaX2241SNffbYmLpYXLgw18582DSrnQ5rzc4CG6HgSWioHZMnavNgtKPVqmKKp3DSZW

**Comment by brandonjamesmarshall** [comment]
Appreciate the work, thank you very much @RantsRoamer!
